#Workflow name

name: test pipeline

on:
  push:
    branches:
      - test

jobs:

  build:
    # Depends on sonar's job
#    needs: sonarcloud
    name: Build
    # Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # build vue
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm

      - name: Install Vue.js dependencies
        run: npm install --force
        working-directory: ui # Path to the Vue.js project directory

      - name: Build Vue.js project
        run: npm run build-production
        working-directory: ui # Path to the Vue.js project directory

      - name: Copy Vue.js build to Java resources
        run: cp -R ui/dist/ src/main/resources/static/


      # build java
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B  package -DskipTests --file pom.xml

      - name: Upload JAR
        # This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
        uses: actions/upload-artifact@v2
        with:
          # Set artifact name
          name: server-test-artifact
          # From this path
          path: target/server.jar

  build-and-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: server-test-artifact
          path: target

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:test-alpine

      - name: Login to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 40020
          script: cd ~ && ./deploy-balance-test.sh wc123456
